### ISSUE TITLE
Tag aliases can be selected

### ISSUE THREAD

**Issue by guettli** [robianmcd/tag-trends#32]
Feature request:

The tag "pwa" is an anlias for "progressive-web-app".

If you go to this link, you get redirect: https://stackoverflow.com/questions/tagged/pwa

This graph shows it, that "pwa" existed only some days: http://sotagtrends.com/?tags=[pwa,progressive-web-apps]

I think it does not make sense that you can select such tags.

I think it would be nice, if tags like "pwa" are not available, since graph you get is wrong.

**Comment by robianmcd** [comment]
Hmm I'm guessing this is some historic data with the pwa tag from before it was aliased. I don't have a good solution for this but I could probably just manually migrate the data with pwa to use progressive-web-app instead

**Comment by robianmcd** [comment]
Should be fixed for pwa now

**Comment by guettli** [comment]
Thank you very much!
