### ISSUE TITLE
Simplify URL (not square brackets)

### ISSUE THREAD

**Issue by guettli** [robianmcd/tag-trends#33]
Several applications don't know that the square brackets (`[`) are valid in URLs.

I have seen it several times, that urlifying from ascii text to HTML don't create valid hyperlinks from sotagtrend URLs.

 
Feature request:

This current URL http://sotagtrends.com/?tags=[pwa,progressive-web-apps]

should be this URL in the future:

http://sotagtrends.com/?tags=[pwa,progressive-web-apps]

http://sotagtrends.com/?tags=pwa+progressive-web-apps

Benefit2: It is easier to type this URL by hand.

BUT: Please provide a redirect from the old URL syntax.

**Comment by robianmcd** [comment]
Yeah I have run into this too. I'll try to fix it when I get some free time

**Comment by robianmcd** [comment]
Should be fixed now

**Comment by guettli** [comment]
Great!
