### ISSUE TITLE
Link from tag to describition of tag

### ISSUE THREAD

**Issue by guettli** [robianmcd/tag-trends#34]
It would be nice if the tag on the page would be a hyperlink to the description at stackoverflow

See this screenshot:

![image](https://user-images.githubusercontent.com/414336/68842661-03c93d00-06c7-11ea-8960-9819287c9899.png)

For example "gruntjs" could be a link to https://stackoverflow.com/tags/gruntjs/info

This is not important, but would be a handy feature. Thank you for this site!

**Comment by robianmcd** [comment]
Good idea. I added this feature

**Comment by guettli** [comment]
Wow, sometimes you just have to make a wish. Thank you!

**Comment by guettli** [comment]
I added this to my guidelines: https://github.com/guettli/programming-guidelines/blob/master/README.md#sometimes-you-just-have-to-speak-out-a-wish

**Comment by robianmcd** [comment]
@guettli  Thanks, and nice guide! I like the analogy of throwing dynamite in a haystack. haha. I'll have to try that one.

**Comment by guettli** [comment]
@robianmcd please tell me any typos or unclear sentences. I am not a native speaker and I think there are sill a lot of mistakes.
